### ISSUE TITLE
Error M_UNAUTHORIZED: Supplied credentials are invalid

### ISSUE THREAD

**Issue by AnassDriate** [ma1uta/ma1sd#125]
```
io.kamax.mxisd.exception.InvalidCredentialsException: Supplied credentials are invalid
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.auth.AccountManager.getUserId(AccountManager.java:86)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.auth.AccountManager.register(AccountManager.java:53)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.http.undertow.handler.auth.v2.AccountRegisterHandler.handleRequest(AccountRegisterHandler.java:54)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]:         at java.lang.Thread.run(Thread.java:748)
Aug 28 13:31:27 u-sm2-gpe matrix-ma1sd[1612694]: [XNIO-1 task-1] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request POST http://u-01.luxchat.lu/_matrix/identity/v2/account/register - Error M_UNAUTHORIZED: Supplied credentials are invalid
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]: [XNIO-1 task-2] ERROR io.kamax.mxisd.auth.AccountManager - Wrong response status: 500
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]: [XNIO-1 task-2] ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Unauthorized:
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]: io.kamax.mxisd.exception.InvalidCredentialsException: Supplied credentials are invalid
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.auth.AccountManager.getUserId(AccountManager.java:86)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.auth.AccountManager.register(AccountManager.java:53)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.http.undertow.handler.auth.v2.AccountRegisterHandler.handleRequest(AccountRegisterHandler.java:54)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
Aug 28 13:31:51 u-sm2-gpe matrix-ma1sd[1612694]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by tomsch** [comment]
have the same issue Matrix Synapse + ma1sd + Element, any workarounds ? Will try to upgrade my Matrix Synapse Version later.

Mobile Element App works fine, only the newest Element Desktop App has the problem.

Old version works fine:
Riot version: 1.9.9
Olm version: 3.2.8

New Desktop  version hast the above problem:

Element version: 1.11.45
Olm version: 3.2.14

Moible App version is fine:
Element 1.11.4
