### ISSUE TITLE
ma1sd allows sql connections to time out

### ISSUE THREAD

**Issue by halkeye** [ma1uta/ma1sd#32]
```
ma1sd-76f7445dc-4crnc ma1sd [XNIO-1 task-12] ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Unknown error when handling http://matrix-identity.g4v.dev/_matrix/identity/v2/account/register
ma1sd-76f7445dc-4crnc ma1sd java.lang.RuntimeException: java.sql.SQLException: Connection has already been closed
ma1sd-76f7445dc-4crnc ma1sd     at io.kamax.mxisd.storage.ormlite.OrmLiteSqlStorage.withCatcher(OrmLiteSqlStorage.java:176)
ma1sd-76f7445dc-4crnc ma1sd     at io.kamax.mxisd.storage.ormlite.OrmLiteSqlStorage.insertToken(OrmLiteSqlStorage.java:310)
ma1sd-76f7445dc-4crnc ma1sd     at io.kamax.mxisd.auth.AccountManager.register(AccountManager.java:60)
ma1sd-76f7445dc-4crnc ma1sd     at io.kamax.mxisd.http.undertow.handler.auth.v2.AccountRegisterHandler.handleRequest(AccountRegisterHandler.java:54)
ma1sd-76f7445dc-4crnc ma1sd     at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
ma1sd-76f7445dc-4crnc ma1sd     at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
ma1sd-76f7445dc-4crnc ma1sd     at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
ma1sd-76f7445dc-4crnc ma1sd     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ma1sd-76f7445dc-4crnc ma1sd     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ma1sd-76f7445dc-4crnc ma1sd     at java.lang.Thread.run(Thread.java:748)
ma1sd-76f7445dc-4crnc ma1sd Caused by: java.sql.SQLException: Connection has already been closed
ma1sd-76f7445dc-4crnc ma1sd     at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:182)
ma1sd-76f7445dc-4crnc ma1sd     at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:327)
ma1sd-76f7445dc-4crnc ma1sd     at io.kamax.mxisd.storage.ormlite.OrmLiteSqlStorage.lambda$insertToken$11(OrmLiteSqlStorage.java:311)
ma1sd-76f7445dc-4crnc ma1sd     at io.kamax.mxisd.storage.ormlite.OrmLiteSqlStorage.withCatcher(OrmLiteSqlStorage.java:174)
ma1sd-76f7445dc-4crnc ma1sd     ... 9 more
```

**Comment by ma1uta** [comment]
Added poll configuration to postgresql in the https://github.com/ma1uta/ma1sd/commit/53c4ffdc4e30c2dba4c5b1233c27f4e38b3c7756
