### ISSUE TITLE
ma1sd fails if it gets a connection refused for well-known URL

### ISSUE THREAD

**Issue by dani** [ma1uta/ma1sd#49]
I'm running a self hosted homeserver. My homeserver name is my top level domain (lapiole.org), and I'm using SRV DNS records to publish the name of the homeserver (matrix.lapiole.org). The top level domain does not run a web server (so I cannot publish well-known files, nor should I need as I have SRV)
ma1sd fails in such a setup to register my 3pids (emails fetched from LDAP). From Riot web, I open preferences, and the POST to /_matrix/identity/v2/account/register gets a 500 error.
In ma1sd log I get : 

```
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: java.lang.RuntimeException: Error while trying to lookup well-known for lapiole.org
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.kamax.mxisd.matrix.HomeserverFederationResolver.resolveWellKnown(HomeserverFederationResolver.java:133)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.kamax.mxisd.matrix.HomeserverFederationResolver.resolve(HomeserverFederationResolver.java:196)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.kamax.mxisd.auth.AccountManager.getUserId(AccountManager.java:69)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.kamax.mxisd.auth.AccountManager.register(AccountManager.java:53)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.kamax.mxisd.http.undertow.handler.auth.v2.AccountRegisterHandler.handleRequest(AccountRegisterHandler.java:54)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.lang.Thread.run(Thread.java:748)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: Caused by: org.apache.http.conn.HttpHostConnectException: Connect to lapiole.org:443 [lapiole.org/10.99.3.12, lapiole.org/10.99.3.13] failed: Connection refused (Connection refused)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at io.kamax.mxisd.matrix.HomeserverFederationResolver.resolveWellKnown(HomeserverFederationResolver.java:114)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: ... 10 more
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.net.PlainSocketImpl.socketConnect(Native Method)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at java.net.Socket.connect(Socket.java:607)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: ... 20 more
Jun 04 23:45:14 mtx matrix-ma1sd[13347]: [XNIO-1 task-1] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request POST http://matrix.lapiole.org/_matrix/identity/v2/account/register - Error M_UNKNOWN: Error while trying to lookup well-known for lapiole.org
```

The problem is here : https://github.com/ma1uta/ma1sd/blob/master/src/main/java/io/kamax/mxisd/matrix/HomeserverFederationResolver.java#L133

Shouldn't failing to connect be treated like non 200, or invalid JSON : just log and go on ?

**Comment by dani** [comment]
The same is true if you run a webserver, with a certificate not valid for this domain
